### ISSUE TITLE
how do you instal this???

### ISSUE THREAD

**Issue by ROBYXOX** [wiiuenjoyer36/JoriPass#3]
u just released the .zip but i actually need either the .3dsx or the .cia to install the app on my console, just like the original Netpass

**Comment by wiiuenjoyer36** [comment]
Hi,

there are no public releases of JoriPass available right now due to some of the features causing issues with NetPass’s servers.

A new .3dsx release will be available once I have modified the code to work properly.

in the meantime, you can attempt to compile JoriPass on your own, or just use the official Netpass app.

-Jori
